ALTER TABLE "PublishJob"
ADD COLUMN "executionStatus" TEXT NOT NULL DEFAULT 'queued',
ADD COLUMN "totalLanes" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "completedLanes" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "failedLanes" INTEGER NOT NULL DEFAULT 0;

ALTER TABLE "PublishLaneResult"
ADD COLUMN "providerMessage" TEXT,
ADD COLUMN "retryable" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "lastAttemptAt" TIMESTAMP(3),
ADD COLUMN "nextRetryAt" TIMESTAMP(3);
